# This is a basic workflow to help you get started with Actions

name: checkcheck

on:
  pull_request_target:
    types: [opened, synchronize]
    branches: [ "main" ]

jobs:
  checkcheckjob:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
