on:
  workflow_dispatch:

jobs:
  reqcjob:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  reuse:
    uses: ./.github/workflows/reusable.yaml
